---
name: Algorithm-Diff-Any
version: 1.001
author:
  - 'Jonathan Yu <jawnsy@cpan.org>'
abstract: Perl module to find differences between files
license: perl
resources:
  Ratings: http://cpanratings.perl.org/d/Algorithm-Diff-Any
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Algorithm-Diff-Any
  license: http://edwardsamuels.com/copyright/beyond/articles/public.html
  repository: http://svn.ali.as/cpan/trunk/Algorithm-Diff-Any
build_requires:
  Test::NoWarnings: 0.084
requires:
  Algorithm::Diff: 1.1902
  Exporter: 5.57
  Test::More: 0.62
  perl: 5.006
recommends:
  Algorithm::Diff::XS: 0
configure_requires:
  Module::Build: 0.35
dynamic_config: 0
provides:
  Algorithm::Diff::Any:
    file: lib/Algorithm/Diff/Any.pm
    version: 1.001
generated_by: Module::Build version 0.35
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
